# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PERSON_ENTERS',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.TextField()),
                ('person_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PERSON_IMAGES',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.TextField()),
                ('image_name', models.TextField()),
                ('person_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PERSONS',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
    ]
