# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wtpersonenters',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('person_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='wtpersonimages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('image_name', models.TextField()),
                ('person_id', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='PERSONS',
            new_name='wtpersons',
        ),
        migrations.DeleteModel(
            name='PERSON_ENTERS',
        ),
        migrations.DeleteModel(
            name='PERSON_IMAGES',
        ),
        migrations.RenameField(
            model_name='wtpersons',
            old_name='date',
            new_name='folder',
        ),
    ]
