# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FR', '0002_auto_20170921_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wtpersonenters',
            name='person_id',
            field=models.IntegerField(),
        ),
    ]
